// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3xD0bGydbuZD9F2DlMDH6kk-hquze4Y',
    appId: '1:621037903956:web:a9a618c0f10c73b73e4dc1',
    messagingSenderId: '621037903956',
    projectId: 'gatorest-inn-6f2ee',
    authDomain: 'gatorest-inn-6f2ee.firebaseapp.com',
    storageBucket: 'gatorest-inn-6f2ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUczohmmdVKvmwgU798pGsvLg6CR3-MM',
    appId: '1:621037903956:android:9e72d13a39b9bb5c3e4dc1',
    messagingSenderId: '621037903956',
    projectId: 'gatorest-inn-6f2ee',
    storageBucket: 'gatorest-inn-6f2ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQN4D5DPC2xakLDBPfcQwA1eqWS0t_Pa0',
    appId: '1:621037903956:ios:12ad8992de70d5883e4dc1',
    messagingSenderId: '621037903956',
    projectId: 'gatorest-inn-6f2ee',
    storageBucket: 'gatorest-inn-6f2ee.appspot.com',
    iosClientId: '621037903956-khgveev73gdnnk53ea4osqa6ekfprdvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosapp',
  );
}
